name: Build GrindrPlus

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew assembleRelease

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GrindrPlus-build
          path: app/build/outputs/apk/release/
